# Generated by Django 5.2.2 on 2025-06-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código do Pedido'),
        ),
    ]
