# Generated by Django 5.2.2 on 2025-06-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.IntegerField(default=1, verbose_name='Código do Pedido'),
            preserve_default=False,
        ),
    ]
