# Generated by Django 5.2.2 on 2025-06-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição'),
        ),
    ]
